#spring.application.name=article
---

server:
  port: 8090
spring:
  application:
    name: article
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
---

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
